development: &DEVELOPMENT
  emails:
    - nick@example.com

test: &TEST
  <<: *DEVELOPMENT

staging: &STAGING
  emails:
    - nick@quaran.to
    - radcliffe.david@gmail.com
    - dev@benjaminfleischer.com

production:
  <<: *STAGING
